path: "/data/yolo_dataset"
train:
  - "/data/yolo_dataset/train/images"
val: "/data/yolo_dataset/val/images"

names:
  0: 'Atelectasis'
  1: 'Cardiomegaly'
  2: 'Effusion'
  3: 'Infiltrate'
  4: 'Mass'
  5: 'Nodule'
  6: 'Pneumonia'
  7: 'Pneumothorax'



#  - "/data/yolo_dataset/augmented/images"
